### PR TITLE
JDBC specific assertions support

### PR DESCRIPTION
**Pull request by spindelmanne**
Adds full support, and convenience methods, for JDBC Timeout assertion and JDBC Status assertion

### CODE REVIEW

**Comment by olensmar** [comment]
ok - should I merge and push this out as 1.0.2 right away?

**Comment by joeljons** [comment]
Code looks good to me!

**Comment by spindelmanne** [comment]
@olensmar Nothing else we want to fix before we make a 1.0.2 version?

**Comment by olensmar** [comment]
nothing I can think of...

**Pull request merged**
